# Generated by Django 4.0.5 on 2022-07-07 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0002_alter_customuser_healthy_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_uuid', models.CharField(max_length=255)),
                ('patient_initials', models.CharField(max_length=255)),
                ('parent_initials', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('age', models.CharField(max_length=255)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('muac', models.CharField(blank=True, max_length=255, null=True)),
                ('symptoms', models.TextField()),
                ('difficulty_breathing', models.CharField(max_length=255)),
                ('days_with_breathing_difficulties', models.CharField(blank=True, max_length=255, null=True)),
                ('hiv_status', models.CharField(blank=True, max_length=255, null=True)),
                ('in_hiv_care', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('febrile_to_touch', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_oxygen_saturation', models.CharField(blank=True, max_length=255, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('breathing_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('respiratory_rate_score', models.CharField(blank=True, max_length=255, null=True)),
                ('respiratory_rate_2', models.CharField(blank=True, max_length=255, null=True)),
                ('breathing_rate_2', models.CharField(blank=True, max_length=255, null=True)),
                ('respiratory_rate_score_2', models.CharField(blank=True, max_length=255, null=True)),
                ('stridor', models.CharField(blank=True, max_length=255, null=True)),
                ('nasal_flaring', models.CharField(blank=True, max_length=255, null=True)),
                ('wheezing', models.CharField(blank=True, max_length=255, null=True)),
                ('wheezing_2', models.CharField(blank=True, max_length=255, null=True)),
                ('stethoscope_used', models.CharField(blank=True, max_length=255, null=True)),
                ('chest_indrawing', models.CharField(blank=True, max_length=255, null=True)),
                ('chest_indrawing_2', models.CharField(blank=True, max_length=255, null=True)),
                ('bronchodilator', models.CharField(blank=True, max_length=255, null=True)),
                ('after_bronchodilator', models.CharField(blank=True, max_length=255, null=True)),
                ('bronchodilator_not_given_reason', models.TextField(blank=True, null=True)),
                ('clinician_diagnosis', models.TextField(blank=True, null=True)),
                ('clinician_treatment', models.TextField(blank=True, null=True)),
                ('end_date', models.DateTimeField()),
                ('diagnosis_1', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_2', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_3', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_4', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_5', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_6', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_7', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_8', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_9', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_10', models.CharField(blank=True, max_length=255, null=True)),
                ('wheezing_before_this_illness', models.CharField(blank=True, max_length=255, null=True)),
                ('child_breathless', models.CharField(blank=True, max_length=255, null=True)),
                ('breathing_difficulties_last_year', models.CharField(blank=True, max_length=255, null=True)),
                ('child_ever_had_eczema', models.CharField(blank=True, max_length=255, null=True)),
                ('child_parents_with_allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('smoke_tobacco', models.CharField(blank=True, max_length=255, null=True)),
                ('use_kerosene', models.CharField(blank=True, max_length=255, null=True)),
                ('incomplete', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
