# Generated by Django 4.0.5 on 2022-08-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0004_rename_in_hiv_care_patient_age2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
