# Generated by Django 4.0.5 on 2022-08-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0006_patient_clinician_2_patient_duration_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_forms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='incomplete_forms',
            field=models.IntegerField(default=0),
        ),
    ]
