# Generated by Django 4.0.5 on 2022-08-30 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0007_customuser_completed_forms_customuser_forms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_indrawing_count', models.CharField(blank=True, max_length=255, null=True)),
                ('grant_count', models.CharField(blank=True, max_length=255, null=True)),
                ('bronchodilator_count', models.CharField(blank=True, max_length=255, null=True)),
                ('wheezing_count', models.CharField(blank=True, max_length=255, null=True)),
                ('stridor_count', models.CharField(blank=True, max_length=255, null=True)),
                ('nasal_count', models.CharField(blank=True, max_length=255, null=True)),
                ('eczema_count', models.CharField(blank=True, max_length=255, null=True)),
                ('rr_counter_count', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_opening_count', models.CharField(blank=True, max_length=255, null=True)),
                ('app_opening_count', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
