# Generated by Django 4.0.5 on 2022-08-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0009_counter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='study_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
