# Generated by Django 4.1.7 on 2023-04-23 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0012_add_code_user_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(max_length=63)),
                ('display_name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('json', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
