# Generated by Django 4.1.7 on 2023-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0014_remove_workflow_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='schema',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
