# Generated by Django 4.1.7 on 2023-05-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0016_tweaks_to_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
