# Generated by Django 4.1.7 on 2023-05-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0017_workflow_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_id',
            field=models.CharField(max_length=63),
        ),
    ]
