# Generated by Django 4.1.7 on 2023-06-06 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alrite', '0019_workflow_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='schema',
        ),
        migrations.CreateModel(
            name='WorkflowPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.IntegerField(default=1)),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alrite.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ValueID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('typeid', models.CharField(max_length=1)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alrite.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='FloatValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alrite.valueid')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alrite.workflowpatient')),
            ],
        ),
        migrations.CreateModel(
            name='CharValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=127)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alrite.valueid')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alrite.workflowpatient')),
            ],
        ),
    ]
